### ISSUE TITLE
Setup dependencies manager bot

### ISSUE THREAD

**Issue by Zuruuh** [Blagues-API/blagues-api-php#6]
Setup a tool like dependabot or renovate (or whatever) to keep project dependencies up to date

**Comment by swiizyy** [comment]
@Zuruuh dependabot ne peut pas gérer sa comme ca ?

```yml
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
```
